namespace UGF.EditorTools.Psd2UGUI
{
    public enum GUIType
    {
        Null = 0,
        Image = 1,
        RawImage = 2,
        Text = 3,
        Button = 4,
        Dropdown = 5,
        InputField = 6,
        Toggle = 7,
        Slider = 8,
        ScrollView = 9,
        Mask = 10,
        FillColor = 11,
        TMPText = 12,
        TMPButton = 13,
        TMPDropdown = 14,
        TMPInputField = 15,
        TMPToggle = 16,
        Panel = 17,
        ToggleGroup = 18,
        Background = 101,
        Button_Highlight = 102,
        Button_Press = 103,
        Button_Select = 104,
        Button_Disable = 105,
        Button_Text = 106,
        Dropdown_Label = 107,
        Dropdown_Arrow = 108,
        InputField_Placeholder = 109,
        InputField_Text = 110,
        Toggle_Checkmark = 111,
        Toggle_Label = 112,
        Slider_Fill = 113,
        Slider_Handle = 114,
        ScrollView_Viewport = 115,
        ScrollView_HorizontalBarBG = 116,
        ScrollView_HorizontalBar = 117,
        ScrollView_VerticalBarBG = 118,
        ScrollView_VerticalBar = 119
    }
}
